### ISSUE TITLE
Section 4

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#27]
Section 4:  Please advise regarding the following:

a) Does "must run in time independent of" mean "must run in a time                                       
that is independent of", or does "independent" refer to "run"
(in which case it should be "independently")?

Original:
 For constant-time implementations, this operation must run in
 time independent of the value of c.

b) Please confirm that (1) the comma before "otherwise" is necessary
and (2) no closing curly brackets are needed.

Original:
 is_square(x) := { True,  if x^((q - 1) / 2) is 0 or 1 in F;
                 { False, otherwise.

**Comment by armfazh** [comment]
for a) it's the former: "must run in a time that is independent of the value of c".

**Comment by armfazh** [comment]
As for (b), the definition of `is_square` is a piecewise function.

There are slight variations regarding punctuation, the text follows the Knuth notation as shown in https://mathworld.wolfram.com/PiecewiseFunction.html

so for b) (1) and (2) are ok.

**Comment by sginoza** [comment]
closing this issue - see #51
