### ISSUE TITLE
Section 6.8 and Appendix D.1: Theorm 3.2

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#29]
Section 6.8 and Appendix D.1:  We could not find a
Theorem 3.2 in [BBJLP08].  Please confirm that readers will be able
to locate the information in question.

Original:
 These curves are closely related to Montgomery curves (Section 6.7):
 every twisted Edwards curve is birationally equivalent to a
 Montgomery curve ([BBJLP08], Theorem 3.2).
...
 The map in this section is a simplified version of the map given in
 [BBJLP08], Theorem 3.2.

**Comment by armfazh** [comment]
The reference points (through a DOI link) to the published paper at springer. In some cases, papers are behind a paywall. 

A free version of the same paper can be found at: https://eprint.iacr.org/2008/013

In the hash to curve document, we tend to cite works using DOI links. This is also recommended by IACR website (https://eprint.iacr.org/citation.html)
