### ISSUE TITLE
Section 10.5: composability of indifferentiability proofs

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#35]
Section 10.5:  We had trouble following this sentence.
Will "By composability of indifferentiability proofs, this also holds"
be clear to readers?

Original:
 By composability of indifferentiability
 proofs, this also holds when expand_message is proved
 indifferentiable from a random oracle relative to an underlying
 primitive that is modeled as a random oracle.

**Comment by armfazh** [comment]
This one is tricky, I understand this text is correct, but I have no better suggestion to improve clarity. 
I defer this one to my coauthors.

**Comment by kwantam** [comment]
Perhaps something like this would be clearer:

"Since indifferentiability proofs are composable, this also holds when expand_message is proved..."

**Comment by sginoza** [comment]
closing this; see #60
