### ISSUE TITLE
Section 10.6: Theorem 3.5

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#36]
Section 10.6:  We could not find a Theorem 3.5 in
[CDMP05] (but we do see a Theorem 3 in Section 3.4 of [CDMP05]).
Should this text be updated?

Original:
 For case (3), i.e., for H a Merkle-Damgaard hash function,
 indifferentiability follows from [CDMP05], Theorem 3.5.

**Comment by armfazh** [comment]
It's true, "Theorem 3.5" does not exist.

It should be either "Section 3.5" (because it contains both Theorem 4 and Theorem 5 and some discussion); or "Theorem 5" (because it's more specific to the construction used).

I'll opt by the former.

**Comment by kwantam** [comment]
Ah. The issue here is that the cite [CDMP05] points to the conference version of the paper, but Theorem 3.5 only appears in the extended version https://cs.nyu.edu/~dodis/ps/merkle.pdf

The cleanest fix is probably just to update the citation.

**Comment by kwantam** [comment]
Mea culpa! @armfazh is correct: we should just change the text to say "Theorem 5" and leave the cite alone :)

**Comment by sginoza** [comment]
closing this issue; see #53
