### ISSUE TITLE
Section 10.7: HKDF-H [RFC5869]

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#38]
Section 10.7:  We could not find "HKDF-H" in RFC 5869.
Will these citations be clear to readers?

Original:
 It
 also applies to HKDF-H [RFC5869], as discussed below.
...
 Finally, this method can be used with HKDF-H [RFC5869] by fixing
 the salt input to HKDF-Extract to DST_key, computed as above.

**Comment by armfazh** [comment]
It follows a parallel construction from the previous sentence, but we may be more specific.


```diff
This method is useful for domain 
separating invocations of H inside HMAC-H (i.e., HMAC [RFC2104]
instantiated with hash function H) from expand_message_xmd. It
- also applies to HKDF-H [RFC5869], as discussed below.
+ also applies to HKDF-H (i.e., HKDF [RFC5869] 
+ instantiated with hash function H), as discussed below.
```

**Comment by sginoza** [comment]
closing this issue; see #54
