### ISSUE TITLE
RPC: make sure this commit gets reviewed and resolved

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#40]
https://github.com/rfc-editor/draft-irtf-cfrg-hash-to-curve/commit/bf4f0619cbfe42e0e698d51132bb8b885f7ecc55

**Comment by armfazh** [comment]
replied in thread https://github.com/rfc-editor/draft-irtf-cfrg-hash-to-curve/commit/bf4f0619cbfe42e0e698d51132bb8b885f7ecc55#commitcomment-115203073

**Comment by sginoza** [comment]
closed; see #62
