### ISSUE TITLE
Consistency: uppercase or lowercase values 

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#47]
Would you like to use uppercase letters or lowercase letters for
the following?

 ASCII characters between 0x21 and 0x7E (inclusive) except that
 underscore (i.e., 0x5f) is not allowed.
...
 underscore ("_", ASCII 0x5f).  This helps to ensure that Suite IDs
...
 colon (":", ASCII 0x3A).

**Comment by kwantam** [comment]
I think capitalized hexadecimal values are slightly easier to read in monospaced font, so I'd vote for caps everywhere.

**Comment by sginoza** [comment]
closing this issue; see #58
