### ISSUE TITLE
hyphyenation: domain separated

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#48]
As "domain separated" appears to be either a verb (e.g.,
"are domain separated from") or an adjective ("a suffix-only domain                               
separated function") and "domain separating" appears to be a verb
(as opposed to "domain that separated" or "domain that separates"),
may we hyphenate these terms as "domain-separated" and
"domain-separating"

**Comment by kwantam** [comment]
Hyphenation sounds right to me! :+1:

**Comment by sginoza** [comment]
closing per #59
