### ISSUE TITLE
Format: use of superscript and/or subscript 

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#49]
Formatting: Once this file is converted to XML, would you like to use superscript and/or subscript throughout?

**Comment by sginoza** [comment]
@armfazh, @samscott89, @grittygrease, @kwantam, @chris-wood

Authors - please review all of the issues labeled "author".  They are ready for your review.

**Comment by kwantam** [comment]
Superscripts and subscripts might be nice, but I worry that there's potential for confusion or inconsistency if we miss a couple, which seems possible in a document this big. So unless others really want them, I'd vote to leave them out.

**Comment by armfazh** [comment]
I would be against if this would require lots of **manual** edits, unless the conversion is automatic. 
Also, not sure if this format renders ok in the TXT version.

**Comment by sginoza** [comment]
closing this out without any updates based on author comments.
