### ISSUE TITLE
IRTF guidelines per RFC 5743

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#8]
Please ensure that the guidelines listed in [Section 2.1
of RFC 5743](https://www.rfc-editor.org/rfc/rfc5743.html#section-2.1) have been adhered to in this document.

**Comment by sginoza** [comment]
@armfazh, @samscott89, @grittygrease, @kwantam, @chris-wood

Authors - please review the issues labeled "author." In an attempt to minimize your @notifications, we will not tag each issue, but we will add @ mentions as new batches of issues are added. If you prefer that we add @ mentions for each issue, please let us know.

**Comment by chris-wood** [comment]
@sginoza do you want us to make a PR for these guideline changes, or is this something you'll take care of?

**Comment by sginoza** [comment]
@chris-wood: If updates are needed, please provide a PR.  We are unable to craft text for things like "breadth of review the document has received" or "[i]f the protocol has been considered in an IETF working group."

**Comment by sginoza** [comment]
@armfazh, @samscott89, @grittygrease, @kwantam, @chris-wood

Hi - checking in on this, as it seems to be the remaining outstanding issue before we convert the file to XML.  Please review and let us know what/if changes are needed. 

Also, please let us know if any other changes are needed before we convert the file to XML.  Once the file has been converted, we do not intend to switch back to markdown.   We will make any needed formatting adjustments to the XML and post the XML and output files for your final review.

**Comment by chris-wood** [comment]
Given that this has passed IRTF chair review as-is, I think the text is probably fine in its current state. So I'm going to go ahead and close this.
