### ISSUE TITLE
Abbreviation expansions

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#9]
For ease of the reader, should the following
abbreviations be expanded?  If yes, please provide the expansions.

 IKM (perhaps "input keying material"?)
 PRK (perhaps "pseudorandom key"?  If yes, may we replace "PRK"
   with "pseudorandom key", since "PRK" is used only once?)
 SWU ("Shallue-van de Woestijne-Ulas", per Section 6.6.2?  We would
   like to expand it in Section 6.1, where it's first used.)

**Comment by chris-wood** [comment]
> IKM (perhaps "input keying material"?)

Fine to expand to "input keying material" on first use!

> PRK (perhaps "pseudorandom key"? If yes, may we replace "PRK" with "pseudorandom key", since "PRK" is used only once?)

Yes, this is fine.

> SWU ("Shallue-van de Woestijne-Ulas", per Section 6.6.2? We would like to expand it in Section 6.1, where it's first used.)

Yes, this is fine.
